name: store_app
description: CLup store application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  scan_preview: ^1.0.0
  permission_handler: ^5.0.1+1
  flutter_secure_storage: ^3.3.5
  shared_preferences: ^0.5.12+4
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

