name: customer_app
description: CLup Customer App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  qr_flutter: ^3.1.0
  flutter_secure_storage: ^3.3.5
  device_info: ^1.0.0
  crypto: ^2.1.5
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
